GRIMY_HERBS = [
    'Grimy avantoe',
    'Grimy cadantine',
    'Grimy dwarf weed',
    'Grimy guam leaf',
    'Grimy harralander',
    'Grimy irit leaf',
    'Grimy kwuarm',
    'Grimy lantadyme',
    'Grimy marrentill',
    'Grimy ranarr weed',
    'Grimy snapdragon',
    'Grimy tarromin',
    'Grimy toadflax',
    'Grimy torstol'
]

HERBS = [
    'Avantoe',
    'Cadantine',
    'Dwarf weed',
    'Guam leaf',
    'Harralander',
    'Irit leaf',
    'Kwuarm',
    'Lantadyme',
    'Marrentill',
    'Ranarr weed',
    'Snapdragon',
    'Tarromin',
    'Toadflax',
    'Torstol',
]

RUNES = [
    'Air rune',
    'Fire rune',
    'Water rune',
    'Earth rune',
    'Body rune',
    'Mind rune',
    'Chaos rune',
    'Law rune',
    'Nature rune',
    'Astral rune',
    'Soul rune',
    'Cosmic rune',
    'Blood rune',
    'Death rune',
    'Wrath rune',
    'Dust rune',
    'Lava rune',
    'Steam rune',
    'Smoke rune',
    'Mud rune',
    'Mist rune',
]